### ISSUE TITLE
when i execute test_hsemotion_package.ipynb, getting an error below.

### ISSUE THREAD

**Issue by ChidanandKumarKS** [HSE-asavchenko/face-emotion-recognition#15]
when i execute test_hsemotion_package.ipynb, getting an error below.

'EfficientNet' object has no attribute 'act1'

Kindly help

**Comment by HSE-asavchenko** [comment]
The issue may be caused by incompatible version of timm package. Could you kindly verify that you have latest version 0.6.7? If so, please, send me more detailed stack trace of your exception. Also, try to run the code from https://github.com/HSE-asavchenko/face-emotion-recognition/blob/main/src/display_emotions.ipynb which does not need the hsemotion package

**Comment by ChidanandKumarKS** [comment]
Thanks [display_emotions.ipynb is working fine. Closing the issue
